jobs:
  include:
    - language: node_js
      node_js:
        - "12"
      before_script:
          - cd client/
      script:
          - npm install && npm run build

    - language: python
      python:
        - "3.6"
      install:
        - pip install setuptools -e .
      before_script:
        - cd server/
      script:
        - pytest
